services:
  severstal.api:
    build:
      context: .
      dockerfile: Severstal.Api/Dockerfile
    ports:
    - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=severstal;Username=postgres;Password=postgres
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
     - "5432:5432"
    environment:
      POSTGRES_DB: Severstal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/posgresql/data
volumes:
  pg_data:
